//510
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.85.08.510")]
[assembly: AssemblyVersion("1.85.08.510")]
