//1033
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.161.03.1033")]
[assembly: AssemblyVersion("1.161.03.1033")]
