//236
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.129.05.236")]
[assembly: AssemblyVersion("1.129.05.236")]
