//1026
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.163.03.1026")]
[assembly: AssemblyVersion("1.163.03.1026")]
