//415
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.92.08.415")]
[assembly: AssemblyVersion("1.92.08.415")]
